export const ABOUT_DEFAULTS = {
  about_hero_title: 'Driven By Trust. Powered By Freedom.',
  about_hero_subtitle: 'Experience the ultimate self-drive freedom. Rent premium, sanitized, and fully insured cars with zero security deposit.',
  
  about_stat_trips: '1,500+',
  about_stat_trips_label: 'Trips Completed',
  about_stat_customers: '2,000+',
  about_stat_customers_label: 'Happy Customers',
  about_stat_vehicles: '100+',
  about_stat_vehicles_label: 'Vehicles in Fleet',
  about_stat_cities: '5+',
  about_stat_cities_label: 'Cities Served',
  
  about_intro_title: 'Driven by Trust. Fueled by Quality.',
  about_intro_desc: 'At our company, our mission is to empower travelers with high-quality, sanitized, and reliable self-drive vehicles. We believe that a journey should be as beautiful as the destination, and that starts with having complete control over your steering wheel.',
  about_intro_location_text: 'Proudly based in Indore, deeply connected to the local travel ecosystem.',

  about_card1_title: 'Sanitized Vehicles',
  about_card1_desc: 'Every car is thoroughly cleaned and sanitized before every trip.',
  about_card1_icon: 'clean_hands',
  about_card2_title: '24x7 Support',
  about_card2_desc: 'Peace of mind guaranteed. We are always just a phone call away.',
  about_card2_icon: 'support_agent',
  about_card3_title: 'GPS Enabled Cars',
  about_card3_desc: 'Track your journey in real time with our secure GPS tracking system.',
  about_card3_icon: 'gps_fixed',
  about_card4_title: 'Luxury Fleet',
  about_card4_desc: 'From premium sedans to capable SUVs, drive the best cars in town.',
  about_card4_icon: 'directions_car',
  about_card5_title: 'Fast Booking',
  about_card5_desc: 'Rent a car in under 5 minutes with our easy online WhatsApp booking.',
  about_card5_icon: 'speed',
  about_card6_title: 'Secure Payments',
  about_card6_desc: 'No hidden fees. Safe and secure transactions via UPI or Net Banking.',
  about_card6_icon: 'security',

  about_founder_name: 'Aditya Patel',
  about_founder_title: 'Founder & CEO',
  about_founder_story: 'Our founder started this self-drive rental company with a simple vision: to make self-drive car rentals premium, accessible, and completely hassle-free. Driven by a deep passion for travel and high-quality customer service, we have grown from a small fleet of 3 cars to a trusted name serving thousands of happy travelers across multiple cities.',
  about_founder_quote: 'We believe every journey should feel premium, comfortable, and completely free.',
  about_founder_avatar_url: '',

  about_why_card1_title: 'Instant Booking',
  about_why_card1_desc: 'Book via WhatsApp in minutes. Quick confirmation and hassle-free paperless verification.',
  about_why_card2_title: 'Wide Fleet Collection',
  about_why_card2_desc: 'Choose from hatchbacks, premium sedans, compact SUVs, and robust 4x4 off-roaders.',
  about_why_card3_title: 'Affordable Pricing',
  about_why_card3_desc: 'Starts at just ₹1200/day. Transparent rates with zero hidden fees or surcharges.',
  about_why_card4_title: 'Fully Maintained Cars',
  about_why_card4_desc: 'All cars undergo regular dealer maintenance and safety checks before dispatch.',
  about_why_card5_title: 'Legal Agreements',
  about_why_card5_desc: 'Fully compliant paperless digital rent agreements signed securely before taking the keys.',
  about_why_card6_title: 'Emergency Support',
  about_why_card6_desc: '24x7 roadside assistance, flat tire support, and immediate backup vehicle arrangement.',

  about_step1_title: 'Choose Vehicle',
  about_step1_desc: 'Browse our fleet and select the car that fits your style and travel needs.',
  about_step2_title: 'Book Online',
  about_step2_desc: 'Confirm your booking details and fuel options quickly via WhatsApp.',
  about_step3_title: 'Verify Documents',
  about_step3_desc: 'Upload your Driving License and Aadhaar card for quick verification.',
  about_step4_title: 'Pickup Vehicle',
  about_step4_desc: 'Collect the keys from our hub or get it delivered straight to your location.',
  about_step5_title: 'Enjoy Ride',
  about_step5_desc: 'Hit the road with complete freedom, unlimited memories, and zero worries.',

  about_safety_card1_title: 'Verified Drivers',
  about_safety_card1_desc: 'We verify all documents to ensure a safe rental community.',
  about_safety_card2_title: 'Sanitized Cars',
  about_safety_card2_desc: 'Deep disinfection protocols inside out before key handover.',
  about_safety_card3_title: 'Insurance Support',
  about_safety_card3_desc: 'Comprehensive insurance coverage for financial security.',
  about_safety_card4_title: 'Secure Payments',
  about_safety_card4_desc: 'Encrypted transactions via UPI, card, or direct bank transfer.',
  about_safety_card5_title: 'GPS Tracking',
  about_safety_card5_desc: 'Live telemetry and GPS enabled fleet for safety checks.',
  about_safety_card6_title: '24x7 Assistance',
  about_safety_card6_desc: 'Round-the-clock emergency support and breakdown assistance.',

  about_cta_title: 'Ready For Your Next Drive?',
  about_cta_desc: 'Experience premium luxury self-drive car rentals with zero deposit today.',
};
