'use client';

import React, { useEffect, useState, Suspense } from 'react';
import { useSearchParams, useRouter } from 'next/navigation';
import Link from 'next/link';
import { getInvoiceById, updateInvoiceStatus } from '@/lib/supabase/queries';
import { DocumentHeader } from '@/components/DocumentHeader';
import type { Invoice } from '@/types';

function InvoicePreviewContent() {
  const searchParams = useSearchParams();
  const id = searchParams.get('id');
  const router = useRouter();
  const [invoice, setInvoice] = useState<any>(null);
  const [paymentMethod, setPaymentMethod] = useState('UPI');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function fetchInvoice() {
      if (id) {
        const data = await getInvoiceById(id);
        if (data) {
          setInvoice(data);
          
          if (searchParams.get('print') === 'true') {
            setTimeout(() => {
              window.print();
            }, 500); // Allow DOM to render visually before jumping to print dialog
          }

          if (searchParams.get('whatsapp') === 'true') {
            setTimeout(async () => {
              const element = document.getElementById('invoice-capture');
              if (element) {
                try {
                  // @ts-ignore
                  const html2pdf = (await import('html2pdf.js')).default || (await import('html2pdf.js'));
                  const opt = {
                    margin:       0.5,
                    filename:     `${data.invoice_number}.pdf`,
                    image:        { type: 'jpeg' as const, quality: 0.98 },
                    html2canvas:  { scale: 2 },
                    jsPDF:        { unit: 'in', format: 'letter', orientation: 'portrait' as const }
                  };
                  html2pdf().set(opt).from(element).save().then(() => {
                    const formatCurrency = (amount: number) => {
                       return new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' }).format(amount);
                    };
                    const text = encodeURIComponent(`Hello ${data.customer_name},\n\nYour invoice ${data.invoice_number} for ${formatCurrency(data.total_amount)} has been generated by Skydeepgroup.\n\nPlease find the attached PDF inside this chat!`);
                    window.location.href = `https://wa.me/${data.customer_phone.replace(/\D/g, '')}?text=${text}`;
                  });
                } catch (e) {
                  console.error('PDF generation error', e);
                }
              }
            }, 800); // Wait for fonts and images
          }
        }
        else router.push('/admin/billing');
      } else {
        router.push('/admin/billing');
      }
      setLoading(false);
    }
    fetchInvoice();
  }, [id, router, searchParams]);

  const handlePrint = () => {
    window.print();
  };

  const markAsPaid = async () => {
    if (invoice && invoice.status !== 'paid') {
      const success = await updateInvoiceStatus(invoice.id, 'paid');
      if (success) {
        setInvoice({ ...invoice, status: 'paid' });
      }
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center p-20">
        <div className="w-8 h-8 border-[3px] border-[#0B1F3A] border-t-transparent rounded-full animate-spin" />
      </div>
    );
  }

  if (!invoice) return null;

  const formatCurrency = (amount: number) => {
     return new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' }).format(amount);
  };

  const formatDate = (dateStr: string) => {
    return new Date(dateStr).toLocaleDateString('en-IN', { month: 'long', day: 'numeric', year: 'numeric' });
  };
  
  const diffDays = Math.ceil(Math.abs(new Date(invoice.end_date).getTime() - new Date(invoice.start_date).getTime()) / (1000 * 60 * 60 * 24)) || 1;

  return (
    <div className="max-w-5xl mx-auto space-y-6">
      <style dangerouslySetInnerHTML={{__html: `
        @media print {
          body * { visibility: hidden; }
          #invoice-capture, #invoice-capture * { visibility: visible; }
          #invoice-capture { position: absolute; left: 0; top: 0; width: 100%; }
          .no-print { display: none !important; }
        }
      `}} />

      {/* Action Bar */}
      <div className="flex justify-between items-end mb-8 no-print animate-in fade-in">
        <div>
          <Link href="/admin/billing" className="text-sm font-bold text-gray-500 hover:text-[#E89B10] flex items-center gap-1 w-fit mb-2">
            <span className="material-symbols-outlined text-[16px]">arrow_back</span>
            Back to Billing
          </Link>
          <h1 className="text-3xl font-black tracking-tight text-[#0B1F3A]">Invoice Preview</h1>
          <p className="text-gray-500">Review the generated tax invoice for {invoice.invoice_number}</p>
        </div>
        <div className="flex gap-3">
          {invoice.status === 'pending' && (
             <button onClick={markAsPaid} className="bg-green-100 text-green-700 px-6 py-3 rounded-xl font-bold hover:bg-green-200 transition-colors flex items-center gap-2">
               <span className="material-symbols-outlined">check_circle</span>
               Mark as Paid
             </button>
          )}
          <button onClick={handlePrint} className="flex items-center gap-2 bg-[#0B1F3A] text-white px-6 py-3 rounded-xl font-bold shadow-lg hover:bg-slate-800 transition-all">
            <span className="material-symbols-outlined">download</span>
            Download PDF
          </button>
        </div>
      </div>

      {/* Invoice Document */}
      <div id="invoice-capture" className="bg-white shadow-xl rounded-2xl p-12 border border-gray-200 relative overflow-hidden animate-in slide-in-from-bottom-4 duration-500">
        
        {/* Header replaced with reusable branding component */}
        <DocumentHeader 
          rightContent={
            <>
              <h2 className="text-4xl sm:text-5xl font-black tracking-tight text-gray-100 uppercase mt-4 sm:mt-0">Invoice</h2>
              <div className="mt-4 space-y-1">
                <p className="text-xs font-bold text-[#E89B10] uppercase tracking-widest">Number</p>
                <p className="font-bold text-lg text-[#0B1F3A]">{invoice.invoice_number}</p>
              </div>
              <div className="mt-4 space-y-1">
                <p className="text-xs font-bold text-gray-400 uppercase tracking-widest">Date Issued</p>
                <p className="font-medium text-gray-700">{formatDate(invoice.created_at)}</p>
              </div>
            </>
          }
        />

        {/* Info Grid */}
        <div className="grid grid-cols-2 gap-12 mb-16 relative z-10">
          <div className="bg-gray-50 p-6 rounded-xl border border-gray-100">
            <h3 className="text-[10px] font-bold uppercase tracking-widest text-gray-400 mb-4">Billing To</h3>
            <div className="space-y-1">
              <p className="font-bold text-lg text-[#0B1F3A]">{invoice.customer_name}</p>
              <p className="text-gray-600">{invoice.customer_address || 'Address not provided'}</p>
              <p className="text-gray-600 mt-2 text-sm flex items-center gap-2"><span className="material-symbols-outlined text-[16px]">call</span> {invoice.customer_phone}</p>
              {invoice.customer_email && (
                 <p className="text-gray-600 text-sm flex items-center gap-2"><span className="material-symbols-outlined text-[16px]">mail</span> {invoice.customer_email}</p>
              )}
            </div>
          </div>
          
          <div className="flex flex-col justify-center border-l-2 border-gray-100 pl-12">
            <h3 className="text-[10px] font-bold uppercase tracking-widest text-gray-400 mb-4">Payment Status</h3>
            <div className="flex items-center gap-3">
              <div className={`w-3 h-3 rounded-full ${invoice.status === 'paid' ? 'bg-green-500 shadow-[0_0_12px_rgba(34,197,94,0.6)]' : 'bg-amber-500 shadow-[0_0_12px_rgba(245,158,11,0.6)]'}`} />
              <span className="font-bold text-2xl uppercase tracking-tight text-[#0B1F3A]">
                {invoice.status === 'paid' ? 'Completed' : 'Awaiting Payment'}
              </span>
            </div>
            {invoice.status === 'pending' && <p className="text-gray-500 text-sm mt-2 font-medium">Due by completion of rental</p>}
          </div>
        </div>

        {/* Line Items */}
        <div className="mb-12 overflow-hidden rounded-xl border border-gray-200">
          <table className="w-full text-left border-collapse">
            <thead className="bg-[#0B1F3A] text-white">
              <tr>
                <th className="px-6 py-4 font-bold text-sm tracking-wider uppercase">Description</th>
                <th className="px-6 py-4 font-bold text-sm tracking-wider uppercase text-right">Rate/Day</th>
                <th className="px-6 py-4 font-bold text-sm tracking-wider uppercase text-center">Duration</th>
                <th className="px-6 py-4 font-bold text-sm tracking-wider uppercase text-right">Amount</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              <tr className="bg-white">
                <td className="px-6 py-6">
                  <div className="font-bold text-[#0B1F3A] text-lg">
                    {invoice.cars?.name || invoice.manual_vehicle_name || 'Vehicle'}
                    {invoice.manual_vehicle_type && !invoice.cars ? ` (${invoice.manual_vehicle_type})` : ''}
                  </div>
                  <div className="text-sm text-gray-500 mt-1">Rental Period: {formatDate(invoice.start_date)} to {formatDate(invoice.end_date)}</div>
                </td>
                <td className="px-6 py-6 text-right font-medium text-gray-700">{formatCurrency(invoice.daily_rate)}</td>
                <td className="px-6 py-6 text-center text-gray-500">{diffDays} Days</td>
                <td className="px-6 py-6 text-right font-bold text-[#0B1F3A]">{formatCurrency(invoice.subtotal)}</td>
              </tr>
            </tbody>
          </table>
        </div>

        {/* Payment & Totals Section */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-4">
           
           {/* Left side: Payment Method & QR code */}
           <div className="space-y-6 pt-2">
              <div>
                <h3 className="text-[10px] font-bold uppercase tracking-widest text-gray-400 mb-3">Payment Method</h3>
                <div className="flex flex-wrap gap-2">
                   {['UPI', 'Cash', 'Debit Card', 'Credit Card'].map((method) => (
                     <button
                       key={method}
                       onClick={() => setPaymentMethod(method)}
                       className={`px-3 py-1.5 rounded-md text-[10px] font-bold uppercase tracking-wider border transition-colors cursor-pointer ${
                         paymentMethod === method 
                           ? (invoice.status === 'paid' ? 'border-[#0B1F3A] bg-[#0B1F3A] text-white shadow-md' : 'border-[#E89B10] bg-[#E89B10]/10 text-[#E89B10]')
                           : 'border-gray-200 text-gray-400 bg-white hover:bg-gray-50'
                       }`}
                     >
                       {method}
                     </button>
                   ))}
                </div>
              </div>

              {invoice.status === 'pending' && (
                <div className="border border-gray-200 bg-white p-4 rounded-xl flex items-center gap-5 max-w-sm shadow-sm ring-1 ring-[#E89B10]/30 animate-in fade-in slide-in-from-bottom-4">
                   <div className="w-24 h-24 bg-white border border-gray-100 rounded-lg p-1 shrink-0 flex items-center justify-center shadow-inner">
                      <img src="/assets/upiqr.png" alt="UPI QR Code" className="max-w-full max-h-full object-contain" />
                   </div>
                   <div className="space-y-1">
                      <h4 className="font-bold text-[#0B1F3A] uppercase tracking-tight text-sm">Scan & Pay</h4>
                      <p className="text-[10px] text-gray-500 leading-relaxed">Pay securely via any UPI app (GPay, PhonePe, Paytm, etc.)</p>
                   </div>
                </div>
              )}
           </div>

           {/* Right side: Totals */}
           <div className="flex flex-col items-end gap-2">
             <div className="w-full space-y-3">
               <div className="flex justify-between items-center text-gray-600">
                 <span>Rental Amount</span>
                 <span className="font-medium text-[#0B1F3A]">{formatCurrency(invoice.subtotal)}</span>
               </div>
               {invoice.gst_enabled && (
                 <div className="flex justify-between items-center text-gray-600">
                   <span>GST (18%)</span>
                   <span className="font-medium text-[#0B1F3A]">{formatCurrency(invoice.tax_amount)}</span>
                 </div>
               )}
               {invoice.security_deposit > 0 && (
                 <div className="flex justify-between items-center text-gray-600">
                   <span className="flex items-center gap-1.5">
                     Security Deposit
                     <span className="text-[9px] bg-green-100 text-green-700 font-bold px-1.5 py-0.5 rounded uppercase tracking-wide">Refundable</span>
                   </span>
                   <span className="font-medium text-[#0B1F3A]">{formatCurrency(invoice.security_deposit)}</span>
                 </div>
               )}
               <div className="h-px bg-gray-200 my-2" />
               <div className="flex justify-between items-center bg-gray-50 border border-gray-200 p-6 rounded-xl relative overflow-hidden">
                 {invoice.status === 'pending' && <div className="absolute top-0 left-0 w-1 h-full bg-[#E89B10]" />}
                 {invoice.status === 'paid' && <div className="absolute top-0 left-0 w-1 h-full bg-green-500" />}
                 <p className="text-[11px] font-black uppercase tracking-widest text-[#0B1F3A]">Total Payable</p>
                 <span className="text-3xl font-black tracking-tighter text-[#E89B10]">{formatCurrency(invoice.total_amount)}</span>
               </div>
               {invoice.security_deposit > 0 && (
                 <p className="text-[9px] text-gray-400 leading-snug">Security Deposit is refundable after vehicle return (subject to terms).</p>
               )}
             </div>
           </div>
           
        </div>

        {/* Additional Terms & Conditions */}
        <div className="mt-12 pt-8 border-t border-gray-200">
           <h3 className="text-[10px] font-bold uppercase tracking-widest text-[#0B1F3A] mb-4">Additional Terms & Conditions</h3>
           <div className="text-[10px] text-gray-500 leading-relaxed text-justify">
             <ol className="list-decimal pl-4 space-y-4">
               <li>
                 <span className="font-bold text-gray-700">Rental Charges:</span><br/>
                 Rental will be charged based on selected duration (6 hours / 12 hours / 24 hours / per day). Additional charges will apply for extra hours or extra kilometers. Fuel cost will be borne by the renter.<br/>
                 <span className="block mt-1">Vehicle usage limits: 150 km for 12 hours | 250 km for 24 hours. The vehicle must be returned to the designated location on time.</span>
               </li>
               <li>
                 <span className="font-bold text-gray-700">Insurance:</span><br/>
                 Only the vehicle is insured. Driver, passengers, and personal belongings are not covered under insurance. In case of an accident, repair costs of the vehicle will be borne by the renter. The company is not responsible for any personal belongings left in the vehicle.
               </li>
               <li>
                 <span className="font-bold text-gray-700">Security Deposit:</span><br/>
                 The renter must pay a refundable security deposit. In case of any damage, the amount will be adjusted against repair costs or deducted from the deposit.
               </li>
               <li>
                 <span className="font-bold text-gray-700">Jurisdiction:</span><br/>
                 All disputes are subject to Indore (M.P.) jurisdiction only.
               </li>
             </ol>
           </div>
        </div>

        {/* Footer info */}
        <div className="mt-16 text-[11px] text-gray-400 border-t border-gray-100 pt-8 flex justify-between items-end">
           <div>
             <p className="font-bold text-[#0B1F3A] uppercase tracking-widest mb-1">Support</p>
             <p>booking@skydeepgroup.com</p>
             <p>+91 91113 30558</p>
           </div>
           <div className="text-right">
             <p className="font-bold text-[#0B1F3A] uppercase tracking-widest">Skydeep Group</p>
             <p>Thank you for choosing us.</p>
           </div>
        </div>
      </div>
    </div>
  );
}

export default function InvoicePreviewPage() {
  return (
    <Suspense fallback={
      <div className="flex items-center justify-center p-20">
        <div className="w-8 h-8 border-[3px] border-[#0B1F3A] border-t-transparent rounded-full animate-spin" />
      </div>
    }>
      <InvoicePreviewContent />
    </Suspense>
  );
}
