'use client';

import React, { useEffect, useState, Suspense } from 'react';
import { useSearchParams, useRouter } from 'next/navigation';
import Link from 'next/link';
import { getInvoiceById, updateInvoiceStatus } from '@/lib/supabase/queries';
import type { Invoice } from '@/types';

function InvoicePreviewContent() {
  const searchParams = useSearchParams();
  const id = searchParams.get('id');
  const router = useRouter();
  const [invoice, setInvoice] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function fetchInvoice() {
      if (id) {
        const data = await getInvoiceById(id);
        if (data) {
          setInvoice(data);
          
          if (searchParams.get('print') === 'true') {
            setTimeout(() => {
              window.print();
            }, 500); // Allow DOM to render visually before jumping to print dialog
          }

          if (searchParams.get('whatsapp') === 'true') {
            setTimeout(async () => {
              const element = document.getElementById('invoice-capture');
              if (element) {
                try {
                  // @ts-ignore
                  const html2pdf = (await import('html2pdf.js')).default || (await import('html2pdf.js'));
                  const opt = {
                    margin:       0.5,
                    filename:     `${data.invoice_number}.pdf`,
                    image:        { type: 'jpeg' as const, quality: 0.98 },
                    html2canvas:  { scale: 2 },
                    jsPDF:        { unit: 'in', format: 'letter', orientation: 'portrait' as const }
                  };
                  html2pdf().set(opt).from(element).save().then(() => {
                    const formatCurrency = (amount: number) => {
                       return new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' }).format(amount);
                    };
                    const text = encodeURIComponent(`Hello ${data.customer_name},\n\nYour invoice ${data.invoice_number} for ${formatCurrency(data.total_amount)} has been generated by Skydeepgroup.\n\nPlease find the attached PDF inside this chat!`);
                    window.location.href = `https://wa.me/${data.customer_phone.replace(/\D/g, '')}?text=${text}`;
                  });
                } catch (e) {
                  console.error('PDF generation error', e);
                }
              }
            }, 800); // Wait for fonts and images
          }
        }
        else router.push('/admin/billing');
      } else {
        router.push('/admin/billing');
      }
      setLoading(false);
    }
    fetchInvoice();
  }, [id, router, searchParams]);

  const handlePrint = () => {
    window.print();
  };

  const markAsPaid = async () => {
    if (invoice && invoice.status !== 'paid') {
      const success = await updateInvoiceStatus(invoice.id, 'paid');
      if (success) {
        setInvoice({ ...invoice, status: 'paid' });
      }
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center p-20">
        <div className="w-8 h-8 border-[3px] border-[#0B1F3A] border-t-transparent rounded-full animate-spin" />
      </div>
    );
  }

  if (!invoice) return null;

  const formatCurrency = (amount: number) => {
     return new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' }).format(amount);
  };

  const formatDate = (dateStr: string) => {
    return new Date(dateStr).toLocaleDateString('en-IN', { month: 'long', day: 'numeric', year: 'numeric' });
  };
  
  const diffDays = Math.ceil(Math.abs(new Date(invoice.end_date).getTime() - new Date(invoice.start_date).getTime()) / (1000 * 60 * 60 * 24)) || 1;

  return (
    <div className="max-w-5xl mx-auto space-y-6">
      <style dangerouslySetInnerHTML={{__html: `
        @media print {
          body * { visibility: hidden; }
          #invoice-capture, #invoice-capture * { visibility: visible; }
          #invoice-capture { position: absolute; left: 0; top: 0; width: 100%; }
          .no-print { display: none !important; }
        }
      `}} />

      {/* Action Bar */}
      <div className="flex justify-between items-end mb-8 no-print animate-in fade-in">
        <div>
          <Link href="/admin/billing" className="text-sm font-bold text-gray-500 hover:text-[#E89B10] flex items-center gap-1 w-fit mb-2">
            <span className="material-symbols-outlined text-[16px]">arrow_back</span>
            Back to Billing
          </Link>
          <h1 className="text-3xl font-black tracking-tight text-[#0B1F3A]">Invoice Preview</h1>
          <p className="text-gray-500">Review the generated tax invoice for {invoice.invoice_number}</p>
        </div>
        <div className="flex gap-3">
          {invoice.status === 'pending' && (
             <button onClick={markAsPaid} className="bg-green-100 text-green-700 px-6 py-3 rounded-xl font-bold hover:bg-green-200 transition-colors flex items-center gap-2">
               <span className="material-symbols-outlined">check_circle</span>
               Mark as Paid
             </button>
          )}
          <button onClick={handlePrint} className="flex items-center gap-2 bg-[#0B1F3A] text-white px-6 py-3 rounded-xl font-bold shadow-lg hover:bg-slate-800 transition-all">
            <span className="material-symbols-outlined">download</span>
            Download PDF
          </button>
        </div>
      </div>

      {/* Invoice Document */}
      <div id="invoice-capture" className="bg-white shadow-xl rounded-2xl p-12 border border-gray-200 relative overflow-hidden animate-in slide-in-from-bottom-4 duration-500">
        
        {/* Header */}
        <div className="flex justify-between items-start mb-16 relative z-10">
          <div className="space-y-4">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 bg-[#0B1F3A] rounded flex items-center justify-center">
                <span className="material-symbols-outlined text-[#E89B10]">directions_car</span>
              </div>
              <span className="font-black text-2xl uppercase tracking-tighter text-[#0B1F3A]">Skydeep<span className="text-[#E89B10]">group</span></span>
            </div>
            <div className="text-gray-500 text-sm leading-relaxed max-w-xs">
              Near HDFC Bank, Ramesh Dosa,<br/>
              Vishnupuri, Bhawarkua, Indore 452001<br/>
              <span className="flex items-center gap-2 mt-2">
                <span className="material-symbols-outlined text-[16px]">phone</span>
                +91 91113 30558
              </span>
              <span className="flex items-center gap-2">
                <span className="material-symbols-outlined text-[16px]">receipt</span>
                GST/VAT: 23AXXPSXXXXX1Z5
              </span>
            </div>
          </div>
          <div className="text-right">
            <h2 className="text-5xl font-black tracking-tight text-gray-100 uppercase">Invoice</h2>
            <div className="mt-4 space-y-1">
              <p className="text-xs font-bold text-[#E89B10] uppercase tracking-widest">Number</p>
              <p className="font-bold text-lg text-[#0B1F3A]">{invoice.invoice_number}</p>
            </div>
            <div className="mt-4 space-y-1">
              <p className="text-xs font-bold text-gray-400 uppercase tracking-widest">Date Issued</p>
              <p className="font-medium text-gray-700">{formatDate(invoice.created_at)}</p>
            </div>
          </div>
        </div>

        {/* Info Grid */}
        <div className="grid grid-cols-2 gap-12 mb-16 relative z-10">
          <div className="bg-gray-50 p-6 rounded-xl border border-gray-100">
            <h3 className="text-[10px] font-bold uppercase tracking-widest text-gray-400 mb-4">Billing To</h3>
            <div className="space-y-1">
              <p className="font-bold text-lg text-[#0B1F3A]">{invoice.customer_name}</p>
              <p className="text-gray-600">{invoice.customer_address || 'Address not provided'}</p>
              <p className="text-gray-600 mt-2 text-sm flex items-center gap-2"><span className="material-symbols-outlined text-[16px]">call</span> {invoice.customer_phone}</p>
              {invoice.customer_email && (
                 <p className="text-gray-600 text-sm flex items-center gap-2"><span className="material-symbols-outlined text-[16px]">mail</span> {invoice.customer_email}</p>
              )}
            </div>
          </div>
          
          <div className="flex flex-col justify-center border-l-2 border-gray-100 pl-12">
            <h3 className="text-[10px] font-bold uppercase tracking-widest text-gray-400 mb-4">Payment Status</h3>
            <div className="flex items-center gap-3">
              <div className={`w-3 h-3 rounded-full ${invoice.status === 'paid' ? 'bg-green-500 shadow-[0_0_12px_rgba(34,197,94,0.6)]' : 'bg-amber-500 shadow-[0_0_12px_rgba(245,158,11,0.6)]'}`} />
              <span className="font-bold text-2xl uppercase tracking-tight text-[#0B1F3A]">
                {invoice.status === 'paid' ? 'Completed' : 'Awaiting Payment'}
              </span>
            </div>
            {invoice.status === 'pending' && <p className="text-gray-500 text-sm mt-2 font-medium">Due by completion of rental</p>}
          </div>
        </div>

        {/* Line Items */}
        <div className="mb-12 overflow-hidden rounded-xl border border-gray-200">
          <table className="w-full text-left border-collapse">
            <thead className="bg-[#0B1F3A] text-white">
              <tr>
                <th className="px-6 py-4 font-bold text-sm tracking-wider uppercase">Description</th>
                <th className="px-6 py-4 font-bold text-sm tracking-wider uppercase text-right">Rate/Day</th>
                <th className="px-6 py-4 font-bold text-sm tracking-wider uppercase text-center">Duration</th>
                <th className="px-6 py-4 font-bold text-sm tracking-wider uppercase text-right">Amount</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              <tr className="bg-white">
                <td className="px-6 py-6">
                  <div className="font-bold text-[#0B1F3A] text-lg">
                    {invoice.cars?.name || invoice.manual_vehicle_name || 'Vehicle'}
                    {invoice.manual_vehicle_type && !invoice.cars ? ` (${invoice.manual_vehicle_type})` : ''}
                  </div>
                  <div className="text-sm text-gray-500 mt-1">Rental Period: {formatDate(invoice.start_date)} to {formatDate(invoice.end_date)}</div>
                </td>
                <td className="px-6 py-6 text-right font-medium text-gray-700">{formatCurrency(invoice.daily_rate)}</td>
                <td className="px-6 py-6 text-center text-gray-500">{diffDays} Days</td>
                <td className="px-6 py-6 text-right font-bold text-[#0B1F3A]">{formatCurrency(invoice.subtotal)}</td>
              </tr>
            </tbody>
          </table>
        </div>

        {/* Totals */}
        <div className="flex flex-col items-end gap-2">
          <div className="w-full md:w-1/2 space-y-4">
            <div className="flex justify-between items-center text-gray-600">
              <span>Subtotal</span>
              <span className="font-medium text-[#0B1F3A]">{formatCurrency(invoice.subtotal)}</span>
            </div>
            {invoice.gst_enabled && (
              <div className="flex justify-between items-center text-gray-600">
                <span>GST (18%)</span>
                <span className="font-medium text-[#0B1F3A]">{formatCurrency(invoice.tax_amount)}</span>
              </div>
            )}
            <div className="h-px bg-gray-200 my-4" />
            <div className="flex justify-between items-center bg-gray-50 border border-gray-200 p-6 rounded-xl">
              <p className="text-[11px] font-black uppercase tracking-widest text-[#0B1F3A]">Total Payable</p>
              <span className="text-3xl font-black tracking-tighter text-[#E89B10]">{formatCurrency(invoice.total_amount)}</span>
            </div>
          </div>
        </div>

        {/* Footer info */}
        <div className="mt-16 text-[11px] text-gray-400 border-t border-gray-100 pt-8 flex justify-between items-end">
           <div>
             <p className="font-bold text-[#0B1F3A] uppercase tracking-widest mb-1">Support</p>
             <p>booking@skydeepgroup.com</p>
             <p>+91 91113 30558</p>
           </div>
           <div className="text-right">
             <p className="font-bold text-[#0B1F3A] uppercase tracking-widest">Skydeep Group</p>
             <p>Thank you for choosing us.</p>
           </div>
        </div>
      </div>
    </div>
  );
}

export default function InvoicePreviewPage() {
  return (
    <Suspense fallback={
      <div className="flex items-center justify-center p-20">
        <div className="w-8 h-8 border-[3px] border-[#0B1F3A] border-t-transparent rounded-full animate-spin" />
      </div>
    }>
      <InvoicePreviewContent />
    </Suspense>
  );
}
